on:
  push:
    branches:
      - main
jobs: 
  build-and-test: 
    runs-on: ubuntu-latest
    steps:

      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.3
      - name: Configure .env file
        env:
          WEATHER: ${{ vars.WEATHER }}
        run: |
          set -e
          mv example.env .env
          sed -i '' "s#WEATHER=.*#WEATHER=$WEATHER#" .env
      - run: flutter pub get
      - run: dart run build_runner build -d
      - run: flutter test
      - run: flutter build apk
      - run: flutter build appbundle
