on:
  push:
    branches:
      - main
defaults:
  run:
    shell: bash
jobs: 
  build-and-test: 
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.3
      # Create the environment file using the github secrets
      - name: Configure .env file
        run: |
          set -e
          touch .env
          echo WEATHER=${{ secrets.WEATHER }} >> .env
      - name: Setup Flutter
        run: |
          flutter pub get
          dart run build_runner build -d
      - name: Run Tests
        run: flutter test
      - name: Build AppBundle
        run: flutter build appbundle
      - name: Build APK
        run: flutter build apk
        # Remove the .env for security - not needed but I feel safer managing it myself :p 
      - name: Clean up Env file 
        run: rm .env
